import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const stable = (value) => `${JSON.stringify(value, null, 2)}\n`;
const digest = (text) => createHash("sha256").update(text).digest("hex");
const full = { left: 0, top: 0, width: 1, height: 1 };
const studyId = "pereira-microzonation";
const approvalText = "la Comisión en pleno aprueba el estudio de microzonificación sísmica del municipio de Pereira";

const sources = [
  { id: "acuerdo-035-2016", issuingAuthority: "Concejo Municipal de Pereira", officialTitle: "Acuerdo 35 de 2016 — Plan de Ordenamiento Territorial", edition: "Acuerdo 35 de 2016", revision: null, adoptionInstrument: "Acuerdo Municipal 35 de 2016", amendmentsAndErrata: [], legalStatus: "active", applicabilityStatus: "conditional", officialUrl: "https://s3.pagegear.co/9/documentos/acuerdos/2115.pdf", retrievedOn: "2026-07-25", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 399, sha256: "90568117201b668164e38f65550350cbfc51d6a111fc5981fcd463e0b487a90e", pages: [{ physicalPage: 106, printedPage: "106", rotationDegrees: 0, crop: full }, { physicalPage: 110, printedPage: "110", rotationDegrees: 0, crop: full }] },
  { id: "cap-acta-201", issuingAuthority: "Comisión Asesora Permanente para el Régimen de Construcciones Sismo Resistentes", officialTitle: "Acta No. 201", edition: "Reunión del 13 de diciembre de 2024", revision: null, adoptionInstrument: "Aprobación técnica de la Comisión; no es decreto municipal", amendmentsAndErrata: [], legalStatus: "historical", applicabilityStatus: "conditional", officialUrl: "https://asosismica.org.co/wp-content/uploads/2025/02/Acta-201-CAP-FINAL_fdo.pdf", retrievedOn: "2026-07-25", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 36, sha256: "500e8d72facae767884494d2f4e8daf7fc2993c951ad89dde41b70825551c787", pages: [{ physicalPage: 1, printedPage: null, rotationDegrees: 0, crop: full }, { physicalPage: 4, printedPage: null, rotationDegrees: 0, crop: full }] },
];
const citations = [
  { id: "pot-legacy-until-new", sourceDocumentId: "acuerdo-035-2016", regionKind: "applicability", physicalPage: 106, printedPage: "106", reference: "Artículo 210, parágrafo 1", rect: full, extractedToken: "se acoge la norma de Sismoresistencia NSR-10, y el Decreto Municipal 932 de 2011 el cual estará vigente hasta la respectiva expedición de la nueva microzonificación sísmica", unit: null, transformation: null, requiredTokens: ["NSR-10", "Decreto Municipal 932 de 2011", "nueva microzonificación sísmica"] },
  { id: "pot-geotechnical-warning", sourceDocumentId: "acuerdo-035-2016", regionKind: "applicability", physicalPage: 110, printedPage: "110", reference: "Artículo 220, parágrafo 2", rect: full, extractedToken: "se acogerán todos los lineamientos y requerimientos de la NSR-10, en particular del Título H en lo referido a los aspectos geotécnicos y el decreto 932 de 2011", unit: null, transformation: null, requiredTokens: ["Título H", "aspectos geotécnicos", "decreto 932 de 2011"] },
  { id: "cap-approval-row", sourceDocumentId: "cap-acta-201", regionKind: "row", physicalPage: 4, printedPage: null, reference: "Numeral 7, Pereira", parentCitationId: "cap-approval-table", rect: { left: 0.08, top: 0.28, width: 0.84, height: 0.25 }, extractedToken: approvalText, unit: null, transformation: null, requiredTokens: ["Comisión", "aprueba", "Pereira"] },
  { id: "cap-approval-table", sourceDocumentId: "cap-acta-201", regionKind: "table", physicalPage: 4, printedPage: null, reference: "Numeral 7. Microzonificaciones sísmicas", rect: full, extractedToken: `Microzonificaciones sísmicas Pereira ${approvalText}`, unit: null, transformation: null, requiredTokens: ["Microzonificaciones sísmicas", "Pereira"] },
  { id: "cap-approval-cell", sourceDocumentId: "cap-acta-201", regionKind: "cell", physicalPage: 4, printedPage: null, reference: "Numeral 7, aprobación técnica de Pereira", parentCitationId: "cap-approval-row", rect: { left: 0.08, top: 0.36, width: 0.84, height: 0.09 }, extractedToken: approvalText, normalizedValue: approvalText, unit: null, transformation: "text identity", requiredTokens: ["aprueba", "Pereira"] },
  { id: "cap-date", sourceDocumentId: "cap-acta-201", regionKind: "applicability", physicalPage: 1, printedPage: null, reference: "Fecha del Acta 201", rect: full, extractedToken: "Viernes 13 de diciembre de 2024", unit: null, transformation: null, requiredTokens: ["13 de diciembre de 2024"] },
];
const manifest = { schemaVersion: 1, studyId, title: "Pereira regulatory-status dossier — spectrum activation blocked", sources, citations, applicabilityCitationIds: ["pot-legacy-until-new", "pot-geotechnical-warning", "cap-date"], coverage: { optionIds: ["pereira-citywide"], hazardIds: ["regulatory-status"], fieldIds: ["cap-approval-status"] }, values: [{ id: "value-pereira-cap-approval", optionId: "pereira-citywide", hazardId: "regulatory-status", fieldId: "cap-approval-status", value: approvalText, unit: null, provenance: "direct-source", citationIds: ["cap-approval-cell"], transformation: "text identity" }], rawRows: [{ id: "raw-pereira-regulatory-status", rowKey: "pereira-citywide/regulatory-status", sourceDocumentId: "cap-acta-201", optionId: "pereira-citywide", hazardId: "regulatory-status", citationIds: ["cap-approval-cell"], fields: { "cap-approval-status": approvalText } }], canonicalRows: [{ id: "canonical-pereira-regulatory-status", rowKey: "pereira-citywide/regulatory-status", sourceDocumentId: "cap-acta-201", optionId: "pereira-citywide", hazardId: "regulatory-status", citationIds: ["cap-approval-cell"], fields: { "cap-approval-status": approvalText }, sourceRowIds: ["raw-pereira-regulatory-status"] }], overrides: [] };
const canonical = { schemaVersion: 1, studyId, status: "research-only-activation-blocked", municipality: "Pereira", regulatoryStatus: "cap-approved-municipal-adoption-and-primary-technical-source-unresolved", proposedSpectrumMatrix: { selectableOptions: [], hazards: [], rows: [] }, historicalRecord: { decree932PrimaryBytesLocated: false, coefficientsCanonicalized: false, formulasCanonicalized: false }, newStudy: { capApprovedOn: "2024-12-13", municipalAdoptionInstrumentLocated: false, primaryTechnicalReportLocated: false }, blockers: ["No municipal decree adopting the CAP-approved study was located.", "The primary technical report, exact zones, coefficients, hazards, damping and formulas were not located.", "Primary official bytes for Decreto 932 de 2011 and its complete technical annex were not located.", "The 2016 POT preserves Decreto 932 until issuance of the new microzonation.", "Professional geotechnical and current municipal-authority verification is required."], capabilities: { traceabilityViewer: true, municipalSpectrumCalculation: false, automaticZoneSelection: false } };
const locks = { schemaVersion: 1, policy: "Both official PDFs remain external-only and are locked by URL, byte length, page count and SHA-256.", locks: [{ sourceDocumentId: sources[0].id, officialUrl: sources[0].officialUrl, retrievedOn: sources[0].retrievedOn, byteLength: 6271986, pageCount: 399, sha256: sources[0].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }, { sourceDocumentId: sources[1].id, officialUrl: sources[1].officialUrl, retrievedOn: sources[1].retrievedOn, byteLength: 769392, pageCount: 36, sha256: sources[1].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }] };
const profile = { schemaVersion: 1, extractor: { engine: "pypdf", version: "6.14.2", ocrUsed: false }, coordinateSystem: "normalized top-left; full-page applicability regions and a bounded CAP approval region", normalization: "Unicode NFC and whitespace collapse", qualityControls: ["No secondary mirror value is transcribed.", "CAP approval is not represented as municipal adoption.", "The proposed spectrum matrix is exactly empty."] };
const attPayload = { schemaVersion: 1, externalOnly: true, sourceHashes: Object.fromEntries(sources.map(({ id, sha256 }) => [id, sha256])), coverage: { regulatoryStatusValues: 1, proposedSpectrumValues: 0, applicabilityClaims: 3, warningClaims: 5, percent: 100 }, attestations: [{ id: "pot-lineage", citationId: "pot-legacy-until-new", textSha256: digest(citations[0].extractedToken) }, { id: "geotechnical-warning", citationId: "pot-geotechnical-warning", textSha256: digest(citations[1].extractedToken) }, { id: "cap-approval", citationId: "cap-approval-cell", textSha256: digest(approvalText) }, { id: "cap-date", citationId: "cap-date", textSha256: digest(citations[5].extractedToken) }], nonInference: "CAP technical approval is not municipal adoption. Missing current adoption and technical bytes block activation." };
const artifacts = {
  "data/canonical.json": canonical,
  "evidence/manifest.json": manifest,
  "evidence/source-locks.json": locks,
  "evidence/extraction-profile.json": profile,
  "evidence/extraction-attestation.json": { ...attPayload, payloadSha256: digest(stable(attPayload)) },
  "evidence/formula-inventory.json": { schemaVersion: 1, status: "unavailable-blocks-activation", proposedProductionFormulas: [], coverage: { expected: 0, cited: 0, rationale: "No production model is proposed." }, missingForActivation: ["all piecewise equations", "all branch bounds", "all parameters and damping/return-period semantics"] },
  "evidence/claims-matrix.json": { schemaVersion: 1, regulatoryStatusMatrix: { expected: 1, cited: 1, coveragePercent: 100 }, proposedSpectrumMatrix: { expected: 0, cited: 0, coverageStatus: "not-applicable-no-adopted-complete-matrix" }, claimCoverage: { applicability: { expected: 3, cited: 3, coveragePercent: 100 }, warnings: { expected: 5, cited: 5, coveragePercent: 100 } }, claims: [{ id: "legacy-rule", statement: "The 2016 POT points to NSR-10 plus Decreto 932 until the new microzonation is issued.", citationId: "pot-legacy-until-new" }, { id: "cap-approval-not-adoption", statement: "Acta 201 records CAP approval of the study; it does not identify a municipal adoption decree.", citationId: "cap-approval-cell" }, { id: "geotechnical", statement: "The POT expressly preserves NSR-10 Title H geotechnical requirements.", citationId: "pot-geotechnical-warning" }] },
  "evidence/uncertainty-ledger.json": { schemaVersion: 1, blocking: true, entries: canonical.blockers.map((issue, index) => ({ id: `blocker-${index + 1}`, severity: "blocker", issue, disposition: "No municipal spectrum activation." })) },
  "evidence/conflict-ledger.json": { schemaVersion: 1, entries: [{ id: "cap-versus-adoption", status: "resolved-for-product", issue: "CAP approved the study but no municipal adoption instrument was located.", resolution: "Treat technical approval and legal adoption as distinct; block activation." }, { id: "legacy-versus-new", status: "resolved-for-product", issue: "POT preserves Decreto 932 until the new microzonation is issued.", resolution: "Do not silently supersede legacy law with the CAP act." }, { id: "secondary-d932-copy", status: "resolved-for-product", issue: "Secondary copies expose possible values/formulas.", resolution: "Do not canonicalize without primary official bytes." }] },
  "evidence/reference-site-differences.json": { schemaVersion: 1, comparison: "Pereira versus Dosquebradas and Santa Rosa de Cabal", materialDifferences: ["Separate municipal adoption chain", "CAP-approved new study", "Pereira-specific legacy Decreto 932", "Unavailable primary technical matrix"], nonInference: "No missing primary-source fact is imported from a neighboring municipality or reference site." },
  "evidence/redistribution.json": { schemaVersion: 1, decision: "external-only-all-sources", committedSourceBytes: false, rationale: "No express redistribution license was found.", prohibitedArtifacts: ["official PDFs", "rendered source pages", "secondary mirrors"] },
  "evidence/review-record.json": { schemaVersion: 1, authorRole: "research agent R7", preparedOn: "2026-07-25", independentReview: { status: "pending", reviewer: null, reviewedOn: null, scope: ["source locks", "CAP/adoption distinction", "POT legacy chain", "zero-spectrum fail-closed decision"] }, activationDecision: "blocked-pending-municipal-adoption-and-primary-technical-source", mergeDecision: "no-merge-for-production-activation" },
};
const check = process.argv.includes("--check"); const mismatches = [];
for (const [relative, value] of Object.entries(artifacts)) { const path = resolve(root, relative); const bytes = stable(value); if (check) { if (await readFile(path, "utf8").catch(() => null) !== bytes) mismatches.push(relative); } else { await mkdir(dirname(path), { recursive: true }); await writeFile(path, bytes, "utf8"); } }
if (mismatches.length) throw new Error(`Generated Pereira artifacts differ: ${mismatches.join(", ")}`);
process.stdout.write(`${check ? "checked" : "generated"} ${Object.keys(artifacts).length} Pereira artifacts\n`);
