import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); const root = resolve(here, "..");
const stable = (value) => `${JSON.stringify(value, null, 2)}\n`; const hash = (value) => createHash("sha256").update(value).digest("hex"); const full = { left: 0, top: 0, width: 1, height: 1 };
const studyId = "santa-rosa-de-cabal-microzonation";
const compatibilityText = "cumplimiento del código de sismo resistencia NRS-10 de acuerdo a la zonificación de suelos definida en la microzonificación sísmica de Santa de Rosa de Cabal";
const sources = [
  { id: "acuerdo-028-2000", issuingAuthority: "Concejo Municipal de Santa Rosa de Cabal", officialTitle: "Acuerdo 028 del 10 de diciembre de 2000 — Plan de Ordenamiento Territorial", edition: "Acuerdo 028 de 2000", revision: null, adoptionInstrument: "Acuerdo Municipal 028 de 2000; incorpora integralmente el Acuerdo 012 de 2000", amendmentsAndErrata: [{ kind: "amendment", reference: "Acuerdo 076 de 2013 — modificación excepcional de norma urbanística", issuedOn: "2013-12-13", officialUrl: "https://www.carder.gov.co/download/1-pbot-santa-rosa-de-cabal-acuerdo-076-de-2013-revision-excepcional/?wpdmdl=5003" }], legalStatus: "active", applicabilityStatus: "conditional", officialUrl: "https://tramites1.suit.gov.co/registro-web/suit_descargar_archivo?A=78028", retrievedOn: "2026-07-25", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 110, sha256: "e3fb9f146c9a00cfecd1faf6f12f61cb44863ffd626e45e3c4121342e15212f8", pages: [{ physicalPage: 69, printedPage: "69", rotationDegrees: 0, crop: full }, { physicalPage: 70, printedPage: "70", rotationDegrees: 0, crop: full }, { physicalPage: 71, printedPage: "71", rotationDegrees: 0, crop: full }] },
  { id: "acuerdo-076-2013", issuingAuthority: "Concejo Municipal de Santa Rosa de Cabal", officialTitle: "Acuerdo 076 de 2013 — modificación excepcional de norma urbanística al PBOT", edition: "13 de diciembre de 2013", revision: null, adoptionInstrument: "Acuerdo Municipal 076 de 2013", amendmentsAndErrata: [], legalStatus: "active", applicabilityStatus: "conditional", officialUrl: "https://www.carder.gov.co/download/1-pbot-santa-rosa-de-cabal-acuerdo-076-de-2013-revision-excepcional/?wpdmdl=5003", retrievedOn: "2026-07-25", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 14, sha256: "16d0c00b293a337d49e51132fc88068a26ec6aad74334c84a2c758e8cd45a346", pages: [{ physicalPage: 1, printedPage: null, rotationDegrees: 0, crop: full }, { physicalPage: 2, printedPage: null, rotationDegrees: 0, crop: full }] },
  { id: "carder-pbot-urban-dts-2000", issuingAuthority: "CARDER / Municipio de Santa Rosa de Cabal", officialTitle: "PBOT Santa Rosa de Cabal — Documento Técnico de Soporte, componente urbano", edition: "PBOT 2000", revision: null, adoptionInstrument: "Soporte técnico del PBOT adoptado por Acuerdo 028 de 2000", amendmentsAndErrata: [], legalStatus: "historical", applicabilityStatus: "applicable", officialUrl: "https://www.carder.gov.co/?wpdmdl=30680", retrievedOn: "2026-07-29", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 113, sha256: "1fe321e2b2daff668b1bb503213458e795ec2e8d9227da3779f5d33517765b43", pages: [{ physicalPage: 96, printedPage: "142", rotationDegrees: 0, crop: full }, { physicalPage: 97, printedPage: "143", rotationDegrees: 0, crop: full }, { physicalPage: 98, printedPage: "144", rotationDegrees: 0, crop: full }] },
];
const citations = [
  { id: "incorporation", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 69, printedPage: "69", reference: "Artículo 80", rect: full, extractedToken: "Incorpórase integralmente como parte del POT, el acuerdo No 012 del 10 de Marzo de 2000, mediante el cual se adoptó la micro zonificación sísmica para Santa Rosa de Cabal", unit: null, transformation: null, requiredTokens: ["acuerdo No 012", "micro zonificación sísmica"] },
  { id: "zones-and-transition", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 70, printedPage: "70", reference: "Artículos 81 y 82.1", rect: full, extractedToken: "Zona 1 Zona 2 Zona 3 Zona 3 A Zona 3 B Zona 4 Zona 5 ... franja de transición de unos 200m a cada lado ... aceleración de diseño más exigente", unit: null, transformation: null, requiredTokens: ["Zona 3 A", "200m", "más exigente"] },
  { id: "geotechnical-and-aa-av", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 70, printedPage: "70", reference: "Artículo 82, numerales 2, 5 y 6", rect: full, extractedToken: "en ningún caso reemplazará la investigación Geotécnica ... NSR-98 ... Aa y Av ... no son válidos ... deben utilizarse ... Am y An", unit: null, transformation: null, requiredTokens: ["investigación Geotécnica", "NSR-98", "Aa", "Av", "Am", "An"] },
  { id: "professional-warning", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 71, printedPage: "71", reference: "Artículo 82, numerales 7 a 11", rect: full, extractedToken: "La mitigación del riesgo sísmico ... no es responsabilidad exclusiva de los ingenieros estructurales ... diversos profesionales y tomadores de decisiones", unit: null, transformation: null, requiredTokens: ["no es responsabilidad exclusiva", "diversos profesionales"] },
  { id: "revision-2013-adoption", sourceDocumentId: "acuerdo-076-2013", regionKind: "applicability", physicalPage: 1, printedPage: null, reference: "Artículos 1 y 2", rect: full, extractedToken: "Adóptese ... la Modificación Excepcional de Norma Urbanística ... Acuerdo 028 del 2000 ... las demás disposiciones continuaran vigentes", unit: null, transformation: null, requiredTokens: ["Modificación Excepcional", "Acuerdo 028 del 2000", "continuaran vigentes"] },
  { id: "urban-dts-five-zones", sourceDocumentId: "carder-pbot-urban-dts-2000", regionKind: "applicability", physicalPage: 96, printedPage: "142", reference: "DTS urbano, microzonificación sísmica", rect: full, extractedToken: "se definieron cinco (5) zonas ... Zona 1 ... Zona 2 ... Zona 3 ... Zona 4 ... Zona 5; la Zona 3 comprende las subáreas 3A y 3B", unit: null, transformation: null, requiredTokens: ["cinco (5) zonas", "Zona 1", "Zona 2"] },
  { id: "urban-dts-transition-am-an", sourceDocumentId: "carder-pbot-urban-dts-2000", regionKind: "applicability", physicalPage: 98, printedPage: "144", reference: "DTS urbano, reglas de transición y coeficientes", rect: full, extractedToken: "franja de transición de unos 200m a cada lado ... aceleración de diseño más exigente que resulte de los espectros de diseño de las zonas adyacentes ... Aa y Av no son válidos ... aceleración máxima Am y aceleración nominal An", unit: null, transformation: null, requiredTokens: ["200m", "más exigente", "Am", "An"] },
  { id: "compatibility-table", sourceDocumentId: "acuerdo-076-2013", regionKind: "table", physicalPage: 2, printedPage: null, reference: "Artículo 65, numerales 5.9, 6.9 y 8.9", rect: full, extractedToken: `NRS-10 microzonificación sísmica ${compatibilityText}`, unit: null, transformation: null, requiredTokens: ["NRS-10", "microzonificación sísmica"] },
  { id: "compatibility-row", sourceDocumentId: "acuerdo-076-2013", regionKind: "row", physicalPage: 2, printedPage: null, reference: "Artículo 65, requisito de altura", parentCitationId: "compatibility-table", rect: { left: 0.05, top: 0.05, width: 0.9, height: 0.9 }, extractedToken: compatibilityText, unit: null, transformation: null, requiredTokens: ["NRS-10", "zonificación de suelos"] },
  { id: "compatibility-cell", sourceDocumentId: "acuerdo-076-2013", regionKind: "cell", physicalPage: 2, printedPage: null, reference: "Artículo 65, requisito sísmico", parentCitationId: "compatibility-row", rect: { left: 0.08, top: 0.08, width: 0.84, height: 0.25 }, extractedToken: compatibilityText, normalizedValue: compatibilityText, unit: null, transformation: "text identity", requiredTokens: ["NRS-10", "Santa de Rosa de Cabal"] },
];
const manifest = { schemaVersion: 1, studyId, title: "Santa Rosa de Cabal historical applicability and numerical-source dossier", sources, citations, applicabilityCitationIds: ["incorporation", "zones-and-transition", "geotechnical-and-aa-av", "professional-warning", "revision-2013-adoption", "urban-dts-five-zones", "urban-dts-transition-am-an"], coverage: { optionIds: ["santa-rosa-citywide"], hazardIds: ["regulatory-status"], fieldIds: ["compatibility-status"] }, values: [{ id: "value-santa-rosa-compatibility", optionId: "santa-rosa-citywide", hazardId: "regulatory-status", fieldId: "compatibility-status", value: compatibilityText, unit: null, provenance: "direct-source", citationIds: ["compatibility-cell"], transformation: "text identity" }], rawRows: [{ id: "raw-santa-rosa-status", rowKey: "santa-rosa-citywide/regulatory-status", sourceDocumentId: "acuerdo-076-2013", optionId: "santa-rosa-citywide", hazardId: "regulatory-status", citationIds: ["compatibility-cell"], fields: { "compatibility-status": compatibilityText } }], canonicalRows: [{ id: "canonical-santa-rosa-status", rowKey: "santa-rosa-citywide/regulatory-status", sourceDocumentId: "acuerdo-076-2013", optionId: "santa-rosa-citywide", hazardId: "regulatory-status", citationIds: ["compatibility-cell"], fields: { "compatibility-status": compatibilityText }, sourceRowIds: ["raw-santa-rosa-status"] }], overrides: [] };
const canonical = { schemaVersion: 1, studyId, status: "research-only-activation-blocked", municipality: "Santa Rosa de Cabal", regulatoryStatus: "historical-microzonation-incorporated-primary-numerical-tables-unavailable", proposedSpectrumMatrix: { selectableOptions: [], hazards: [], rows: [] }, documentedDesignZones: [{ id: "zone-1", label: "Zona 1 — La Hermosa", subareas: [] }, { id: "zone-2", label: "Zona 2 — Centro Estadio", subareas: [] }, { id: "zone-3", label: "Zona 3 — Guacas / occidental Q. San Roque / Monserrate", subareas: ["3A", "3B"] }, { id: "zone-4", label: "Zona 4 — río San Eugenio y quebrada San Roque", subareas: [] }, { id: "zone-5", label: "Zona 5 — Los Andes / Lorencita Villegas", subareas: [] }], transitionRule: "approximately 200 m on each side; use the more demanding adjacent design spectrum/acceleration", coefficientRule: "Am and An replace Aa and Av when the municipal microzonation spectra apply", blockers: ["The primary Am/An coefficient table and exact spectrum equations were not recovered from an official source.", "Exact hazards, return periods, damping, piecewise branches and bound inclusivity remain unavailable."], warnings: ["The separate official bytes for Acuerdo 012 and its complete technical annex were not recovered; incorporation is proved through Acuerdo 028 and the official PBOT DTS.", "Zone selection remains manual and professionally verified; no GIS automation is authorized."], capabilities: { traceabilityViewer: true, municipalSpectrumCalculation: false, automaticZoneSelection: false } };
const locks = { schemaVersion: 1, policy: "Official PDFs remain external-only and are locked by URL, byte length, page count and SHA-256.", locks: [{ sourceDocumentId: sources[0].id, officialUrl: sources[0].officialUrl, retrievedOn: sources[0].retrievedOn, byteLength: 962304, pageCount: 110, sha256: sources[0].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }, { sourceDocumentId: sources[1].id, officialUrl: sources[1].officialUrl, retrievedOn: sources[1].retrievedOn, byteLength: 261815, pageCount: 14, sha256: sources[1].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }, { sourceDocumentId: sources[2].id, officialUrl: sources[2].officialUrl, retrievedOn: sources[2].retrievedOn, byteLength: 809300, pageCount: 113, sha256: sources[2].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }] };
const profile = { schemaVersion: 1, extractor: { engine: "pypdf", version: "6.14.2", ocrUsed: false }, coordinateSystem: "normalized top-left; full-page clauses and bounded direct status cell", normalization: "Unicode NFC and whitespace collapse", qualityControls: ["No coefficient or equation from a secondary mirror is used.", "Five design zones are recorded; 3A and 3B are subareas of Zone 3, not additional design zones.", "NSR-98/2013 NRS-10 context is recorded without making it a blanket legal blocker."] };
const attPayload = { schemaVersion: 1, externalOnly: true, sourceHashes: Object.fromEntries(sources.map(({ id, sha256 }) => [id, sha256])), coverage: { regulatoryStatusValues: 1, proposedSpectrumValues: 0, applicabilityClaims: 7, warningClaims: 2, percent: 100 }, attestations: citations.filter(({ id }) => ["incorporation", "zones-and-transition", "geotechnical-and-aa-av", "professional-warning", "revision-2013-adoption", "urban-dts-five-zones", "urban-dts-transition-am-an", "compatibility-cell"].includes(id)).map(({ id, sourceDocumentId, physicalPage, extractedToken }) => ({ citationId: id, sourceDocumentId, physicalPage, textSha256: hash(extractedToken) })), nonInference: "Official PBOT sources confirm incorporation, five design zones, the transition rule and Am/An terminology; only the exact numerical package remains unavailable." };
const artifacts = {
  "data/canonical.json": canonical, "evidence/manifest.json": manifest, "evidence/source-locks.json": locks, "evidence/extraction-profile.json": profile, "evidence/extraction-attestation.json": { ...attPayload, payloadSha256: hash(stable(attPayload)) },
  "evidence/formula-inventory.json": { schemaVersion: 1, status: "unavailable-blocks-activation", proposedProductionFormulas: [], coverage: { expected: 0, cited: 0, rationale: "No production model is proposed." }, missingForActivation: ["Am and An values", "piecewise equations", "branch bounds and inclusivity", "hazard/return-period/damping semantics"] },
  "evidence/claims-matrix.json": { schemaVersion: 1, regulatoryStatusMatrix: { expected: 1, cited: 1, coveragePercent: 100 }, proposedSpectrumMatrix: { expected: 0, cited: 0, coverageStatus: "not-applicable-primary-am-an-table-and-equations-unavailable" }, claimCoverage: { applicability: { expected: 7, cited: 7, coveragePercent: 100 }, warnings: { expected: 2, cited: 2, coveragePercent: 100 } }, claims: [{ id: "incorporated", statement: "Acuerdo 028 incorporates Acuerdo 012's microzonation.", citationId: "incorporation" }, { id: "five-design-zones", statement: "The official urban DTS defines five design zones; 3A and 3B are subareas of Zone 3.", citationId: "urban-dts-five-zones" }, { id: "transition", statement: "The transition strip is approximately 200 m each side and uses the more demanding adjacent spectrum/acceleration.", citationId: "urban-dts-transition-am-an" }, { id: "geotechnical", statement: "The municipal spectrum never replaces project geotechnical investigation.", citationId: "geotechnical-and-aa-av" }, { id: "aa-av", statement: "Aa and Av are not valid with the municipal spectra; Am and An are the identified replacements.", citationId: "urban-dts-transition-am-an" }, { id: "later-nsr10-reference", statement: "The 2013 modification references NRS-10 together with the adopted municipal soil zoning.", citationId: "compatibility-cell" }] },
  "evidence/uncertainty-ledger.json": { schemaVersion: 1, blocking: true, entries: canonical.blockers.map((issue, index) => ({ id: `blocker-${index + 1}`, severity: "blocker", issue, disposition: "No municipal spectrum activation." })) },
  "evidence/conflict-ledger.json": { schemaVersion: 1, entries: [{ id: "nsr98-versus-nrs10", status: "resolved-for-product", issue: "Acuerdo 028 names NSR-98; Acuerdo 076 later names NRS-10 in selected height provisions.", resolution: "Record both as context; this is not a blanket blocker to the incorporated historical model." }, { id: "acuerdo012-bytes-missing", status: "resolved-for-product", issue: "Acuerdo 028 incorporates Acuerdo 012, but separate official bytes for Acuerdo 012 were not located.", resolution: "Preserve the official incorporation finding; keep only the missing numerical annex as an activation gap." }, { id: "five-zones-versus-seven-labels", status: "resolved-for-product", issue: "Earlier wording counted 3A/3B as separate design zones.", resolution: "Use five design zones and record 3A/3B as Zone 3 subareas." }] },
  "evidence/reference-site-differences.json": { schemaVersion: 1, comparison: "Santa Rosa de Cabal versus Pereira, Dosquebradas and EspectroCol UX", materialDifferences: ["Acuerdo 012/028/076 incorporation lineage", "Five design zones with 3A/3B as Zone 3 subareas", "200 m transition and governing-adjacent rule", "Am/An instead of Aa/Av under the historical clause"], nonInference: "No neighboring-city or reference-site coefficient, formula, hazard, or legal effect is imported." },
  "evidence/redistribution.json": { schemaVersion: 1, decision: "external-only-all-sources", committedSourceBytes: false, rationale: "No express redistribution license was found.", prohibitedArtifacts: ["official PDFs", "rendered pages", "maps/GIS layers", "secondary mirrors"] },
  "evidence/review-record.json": { schemaVersion: 1, authorRole: "research agent R7", preparedOn: "2026-07-29", independentReview: { status: "pending", reviewer: null, reviewedOn: null, scope: ["source locks", "five-zone classification", "transition and Am/An rules", "localized numerical gap"] }, activationDecision: "blocked-only-by-missing-primary-am-an-table-and-equations", mergeDecision: "evidence-may-merge-calculation-remains-unavailable" },
};
const check = process.argv.includes("--check"); const mismatches = [];
for (const [relative, value] of Object.entries(artifacts)) { const path = resolve(root, relative); const bytes = stable(value); if (check) { if (await readFile(path, "utf8").catch(() => null) !== bytes) mismatches.push(relative); } else { await mkdir(dirname(path), { recursive: true }); await writeFile(path, bytes, "utf8"); } }
if (mismatches.length) throw new Error(`Generated Santa Rosa artifacts differ: ${mismatches.join(", ")}`); process.stdout.write(`${check ? "checked" : "generated"} ${Object.keys(artifacts).length} Santa Rosa artifacts\n`);
