import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); const root = resolve(here, "..");
const stable = (value) => `${JSON.stringify(value, null, 2)}\n`; const hash = (value) => createHash("sha256").update(value).digest("hex"); const full = { left: 0, top: 0, width: 1, height: 1 };
const studyId = "santa-rosa-de-cabal-microzonation";
const compatibilityText = "cumplimiento del código de sismo resistencia NRS-10 de acuerdo a la zonificación de suelos definida en la microzonificación sísmica de Santa de Rosa de Cabal";
const sources = [
  { id: "acuerdo-028-2000", issuingAuthority: "Concejo Municipal de Santa Rosa de Cabal", officialTitle: "Acuerdo 028 del 10 de diciembre de 2000 — Plan de Ordenamiento Territorial", edition: "Acuerdo 028 de 2000", revision: null, adoptionInstrument: "Acuerdo Municipal 028 de 2000; incorpora integralmente el Acuerdo 012 de 2000", amendmentsAndErrata: [{ kind: "amendment", reference: "Acuerdo 076 de 2013 — modificación excepcional de norma urbanística", issuedOn: "2013-12-13", officialUrl: "https://www.carder.gov.co/download/1-pbot-santa-rosa-de-cabal-acuerdo-076-de-2013-revision-excepcional/?wpdmdl=5003" }], legalStatus: "active", applicabilityStatus: "conditional", officialUrl: "https://tramites1.suit.gov.co/registro-web/suit_descargar_archivo?A=78028", retrievedOn: "2026-07-25", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 110, sha256: "e3fb9f146c9a00cfecd1faf6f12f61cb44863ffd626e45e3c4121342e15212f8", pages: [{ physicalPage: 69, printedPage: "69", rotationDegrees: 0, crop: full }, { physicalPage: 70, printedPage: "70", rotationDegrees: 0, crop: full }, { physicalPage: 71, printedPage: "71", rotationDegrees: 0, crop: full }] },
  { id: "acuerdo-076-2013", issuingAuthority: "Concejo Municipal de Santa Rosa de Cabal", officialTitle: "Acuerdo 076 de 2013 — modificación excepcional de norma urbanística al PBOT", edition: "13 de diciembre de 2013", revision: null, adoptionInstrument: "Acuerdo Municipal 076 de 2013", amendmentsAndErrata: [], legalStatus: "active", applicabilityStatus: "conditional", officialUrl: "https://www.carder.gov.co/download/1-pbot-santa-rosa-de-cabal-acuerdo-076-de-2013-revision-excepcional/?wpdmdl=5003", retrievedOn: "2026-07-25", redistribution: { decision: "external-only", rationale: "No se localizó licencia expresa de redistribución; se conserva URL y huella." }, mediaType: "application/pdf", pageCount: 14, sha256: "16d0c00b293a337d49e51132fc88068a26ec6aad74334c84a2c758e8cd45a346", pages: [{ physicalPage: 1, printedPage: null, rotationDegrees: 0, crop: full }, { physicalPage: 2, printedPage: null, rotationDegrees: 0, crop: full }] },
];
const citations = [
  { id: "incorporation", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 69, printedPage: "69", reference: "Artículo 80", rect: full, extractedToken: "Incorpórase integralmente como parte del POT, el acuerdo No 012 del 10 de Marzo de 2000, mediante el cual se adoptó la micro zonificación sísmica para Santa Rosa de Cabal", unit: null, transformation: null, requiredTokens: ["acuerdo No 012", "micro zonificación sísmica"] },
  { id: "zones-and-transition", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 70, printedPage: "70", reference: "Artículos 81 y 82.1", rect: full, extractedToken: "Zona 1 Zona 2 Zona 3 Zona 3 A Zona 3 B Zona 4 Zona 5 ... franja de transición de unos 200m a cada lado ... aceleración de diseño más exigente", unit: null, transformation: null, requiredTokens: ["Zona 3 A", "200m", "más exigente"] },
  { id: "geotechnical-and-aa-av", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 70, printedPage: "70", reference: "Artículo 82, numerales 2, 5 y 6", rect: full, extractedToken: "en ningún caso reemplazará la investigación Geotécnica ... NSR-98 ... Aa y Av ... no son válidos ... deben utilizarse ... Am y An", unit: null, transformation: null, requiredTokens: ["investigación Geotécnica", "NSR-98", "Aa", "Av", "Am", "An"] },
  { id: "professional-warning", sourceDocumentId: "acuerdo-028-2000", regionKind: "applicability", physicalPage: 71, printedPage: "71", reference: "Artículo 82, numerales 7 a 11", rect: full, extractedToken: "La mitigación del riesgo sísmico ... no es responsabilidad exclusiva de los ingenieros estructurales ... diversos profesionales y tomadores de decisiones", unit: null, transformation: null, requiredTokens: ["no es responsabilidad exclusiva", "diversos profesionales"] },
  { id: "revision-2013-adoption", sourceDocumentId: "acuerdo-076-2013", regionKind: "applicability", physicalPage: 1, printedPage: null, reference: "Artículos 1 y 2", rect: full, extractedToken: "Adóptese ... la Modificación Excepcional de Norma Urbanística ... Acuerdo 028 del 2000 ... las demás disposiciones continuaran vigentes", unit: null, transformation: null, requiredTokens: ["Modificación Excepcional", "Acuerdo 028 del 2000", "continuaran vigentes"] },
  { id: "compatibility-table", sourceDocumentId: "acuerdo-076-2013", regionKind: "table", physicalPage: 2, printedPage: null, reference: "Artículo 65, numerales 5.9, 6.9 y 8.9", rect: full, extractedToken: `NRS-10 microzonificación sísmica ${compatibilityText}`, unit: null, transformation: null, requiredTokens: ["NRS-10", "microzonificación sísmica"] },
  { id: "compatibility-row", sourceDocumentId: "acuerdo-076-2013", regionKind: "row", physicalPage: 2, printedPage: null, reference: "Artículo 65, requisito de altura", parentCitationId: "compatibility-table", rect: { left: 0.05, top: 0.05, width: 0.9, height: 0.9 }, extractedToken: compatibilityText, unit: null, transformation: null, requiredTokens: ["NRS-10", "zonificación de suelos"] },
  { id: "compatibility-cell", sourceDocumentId: "acuerdo-076-2013", regionKind: "cell", physicalPage: 2, printedPage: null, reference: "Artículo 65, requisito sísmico", parentCitationId: "compatibility-row", rect: { left: 0.08, top: 0.08, width: 0.84, height: 0.25 }, extractedToken: compatibilityText, normalizedValue: compatibilityText, unit: null, transformation: "text identity", requiredTokens: ["NRS-10", "Santa de Rosa de Cabal"] },
];
const manifest = { schemaVersion: 1, studyId, title: "Santa Rosa de Cabal regulatory-status dossier — spectrum activation blocked", sources, citations, applicabilityCitationIds: ["incorporation", "zones-and-transition", "geotechnical-and-aa-av", "professional-warning", "revision-2013-adoption"], coverage: { optionIds: ["santa-rosa-citywide"], hazardIds: ["regulatory-status"], fieldIds: ["compatibility-status"] }, values: [{ id: "value-santa-rosa-compatibility", optionId: "santa-rosa-citywide", hazardId: "regulatory-status", fieldId: "compatibility-status", value: compatibilityText, unit: null, provenance: "direct-source", citationIds: ["compatibility-cell"], transformation: "text identity" }], rawRows: [{ id: "raw-santa-rosa-status", rowKey: "santa-rosa-citywide/regulatory-status", sourceDocumentId: "acuerdo-076-2013", optionId: "santa-rosa-citywide", hazardId: "regulatory-status", citationIds: ["compatibility-cell"], fields: { "compatibility-status": compatibilityText } }], canonicalRows: [{ id: "canonical-santa-rosa-status", rowKey: "santa-rosa-citywide/regulatory-status", sourceDocumentId: "acuerdo-076-2013", optionId: "santa-rosa-citywide", hazardId: "regulatory-status", citationIds: ["compatibility-cell"], fields: { "compatibility-status": compatibilityText }, sourceRowIds: ["raw-santa-rosa-status"] }], overrides: [] };
const canonical = { schemaVersion: 1, studyId, status: "research-only-activation-blocked", municipality: "Santa Rosa de Cabal", regulatoryStatus: "legacy-microzonation-preserved-but-complete-current-calculation-model-unavailable", proposedSpectrumMatrix: { selectableOptions: [], hazards: [], rows: [] }, documentedZoneLabels: ["Zona 1 — La Hermosa", "Zona 2 — Centro Estadio", "Zona 3 — Guacas / occidental Q. San Roque / Monserrate", "Zona 3A — Guacas y Jazmín-El Lembo", "Zona 3B — áreas montañosas este y occidental", "Zona 4 — río San Eugenio y quebrada San Roque", "Zona 5 — Los Andes / Lorencita Villegas"], transitionRule: "approximately 200 m on each side; use the more demanding adjacent design acceleration", blockers: ["Primary official bytes for Acuerdo 012 de 2000 and its complete technical annex were not located.", "No primary coefficient tables or Am/An values were located.", "No complete current formulas, branch inclusivity, hazards, return periods or damping were located.", "Acuerdo 028 frames the technical rule under NSR-98 while Acuerdo 076 references NRS-10 for selected urban height provisions without republishing the technical model.", "Zone selection must remain manual and professionally verified; no GIS automation is authorized."], capabilities: { traceabilityViewer: true, municipalSpectrumCalculation: false, automaticZoneSelection: false } };
const locks = { schemaVersion: 1, policy: "Official PDFs remain external-only and are locked by URL, byte length, page count and SHA-256.", locks: [{ sourceDocumentId: sources[0].id, officialUrl: sources[0].officialUrl, retrievedOn: sources[0].retrievedOn, byteLength: 962304, pageCount: 110, sha256: sources[0].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }, { sourceDocumentId: sources[1].id, officialUrl: sources[1].officialUrl, retrievedOn: sources[1].retrievedOn, byteLength: 261815, pageCount: 14, sha256: sources[1].sha256, mediaType: "application/pdf", redistributionDecision: "external-only" }] };
const profile = { schemaVersion: 1, extractor: { engine: "pypdf", version: "6.14.2", ocrUsed: false }, coordinateSystem: "normalized top-left; full-page clauses and bounded direct status cell", normalization: "Unicode NFC and whitespace collapse", qualityControls: ["No coefficient or equation from a secondary mirror is used.", "The seven labels are recorded only as documentary metadata, not selectable calculator options.", "NSR-98/2013 NRS-10 tension is not silently reconciled."] };
const attPayload = { schemaVersion: 1, externalOnly: true, sourceHashes: Object.fromEntries(sources.map(({ id, sha256 }) => [id, sha256])), coverage: { regulatoryStatusValues: 1, proposedSpectrumValues: 0, applicabilityClaims: 5, warningClaims: 5, percent: 100 }, attestations: citations.filter(({ id }) => ["incorporation", "zones-and-transition", "geotechnical-and-aa-av", "professional-warning", "revision-2013-adoption", "compatibility-cell"].includes(id)).map(({ id, sourceDocumentId, physicalPage, extractedToken }) => ({ citationId: id, sourceDocumentId, physicalPage, textSha256: hash(extractedToken) })), nonInference: "The later instrument preserves the microzonation reference but does not supply a complete current calculation model." };
const artifacts = {
  "data/canonical.json": canonical, "evidence/manifest.json": manifest, "evidence/source-locks.json": locks, "evidence/extraction-profile.json": profile, "evidence/extraction-attestation.json": { ...attPayload, payloadSha256: hash(stable(attPayload)) },
  "evidence/formula-inventory.json": { schemaVersion: 1, status: "unavailable-blocks-activation", proposedProductionFormulas: [], coverage: { expected: 0, cited: 0, rationale: "No production model is proposed." }, missingForActivation: ["Am and An values", "piecewise equations", "branch bounds and inclusivity", "hazard/return-period/damping semantics"] },
  "evidence/claims-matrix.json": { schemaVersion: 1, regulatoryStatusMatrix: { expected: 1, cited: 1, coveragePercent: 100 }, proposedSpectrumMatrix: { expected: 0, cited: 0, coverageStatus: "not-applicable-no-complete-current-primary-matrix" }, claimCoverage: { applicability: { expected: 5, cited: 5, coveragePercent: 100 }, warnings: { expected: 5, cited: 5, coveragePercent: 100 } }, claims: [{ id: "incorporated", statement: "Acuerdo 028 incorporates Acuerdo 012's microzonation.", citationId: "incorporation" }, { id: "transition", statement: "The transition strip is approximately 200 m each side and uses the more demanding adjacent acceleration.", citationId: "zones-and-transition" }, { id: "geotechnical", statement: "The municipal spectrum never replaces project geotechnical investigation.", citationId: "geotechnical-and-aa-av" }, { id: "aa-av", statement: "Aa and Av are not valid with the municipal spectra; the text points to Am and An equivalents.", citationId: "geotechnical-and-aa-av" }, { id: "later-nsr10-reference", statement: "The 2013 modification references NRS-10 together with the adopted municipal soil zoning.", citationId: "compatibility-cell" }] },
  "evidence/uncertainty-ledger.json": { schemaVersion: 1, blocking: true, entries: canonical.blockers.map((issue, index) => ({ id: `blocker-${index + 1}`, severity: "blocker", issue, disposition: "No municipal spectrum activation." })) },
  "evidence/conflict-ledger.json": { schemaVersion: 1, entries: [{ id: "nsr98-versus-nrs10", status: "resolved-for-product", issue: "Acuerdo 028 names NSR-98; Acuerdo 076 later names NRS-10 in selected height provisions.", resolution: "Record both exact clauses; do not invent a harmonized equation set." }, { id: "acuerdo012-missing", status: "resolved-for-product", issue: "Acuerdo 028 incorporates Acuerdo 012, but the latter's complete primary package was not located.", resolution: "Preserve legal lineage and warnings; ship zero spectrum rows." }, { id: "zone-labels-without-values", status: "resolved-for-product", issue: "Zone labels are official but coefficient/formula tables are unavailable.", resolution: "Document labels without making them calculator-selectable." }] },
  "evidence/reference-site-differences.json": { schemaVersion: 1, comparison: "Santa Rosa de Cabal versus Pereira and Dosquebradas", materialDifferences: ["Acuerdo 012/028/076 adoption lineage", "Seven named zones including 3A/3B", "200 m transition and governing-adjacent rule", "Am/An instead of Aa/Av under the legacy clause"], nonInference: "No neighboring-city coefficient, formula, hazard, or legal effect is imported." },
  "evidence/redistribution.json": { schemaVersion: 1, decision: "external-only-all-sources", committedSourceBytes: false, rationale: "No express redistribution license was found.", prohibitedArtifacts: ["official PDFs", "rendered pages", "maps/GIS layers", "secondary mirrors"] },
  "evidence/review-record.json": { schemaVersion: 1, authorRole: "research agent R7", preparedOn: "2026-07-25", independentReview: { status: "pending", reviewer: null, reviewedOn: null, scope: ["source locks", "Acuerdo 012/028/076 lineage", "NSR compatibility conflict", "warnings and zero-spectrum decision"] }, activationDecision: "blocked-missing-complete-current-primary-calculation-model", mergeDecision: "no-merge-for-production-activation" },
};
const check = process.argv.includes("--check"); const mismatches = [];
for (const [relative, value] of Object.entries(artifacts)) { const path = resolve(root, relative); const bytes = stable(value); if (check) { if (await readFile(path, "utf8").catch(() => null) !== bytes) mismatches.push(relative); } else { await mkdir(dirname(path), { recursive: true }); await writeFile(path, bytes, "utf8"); } }
if (mismatches.length) throw new Error(`Generated Santa Rosa artifacts differ: ${mismatches.join(", ")}`); process.stdout.write(`${check ? "checked" : "generated"} ${Object.keys(artifacts).length} Santa Rosa artifacts\n`);
