import { checkEvidenceStudy } from "../runtime.mjs";

export const studyId = "framework-fixture";

const fullPage = { left: 0, top: 0, width: 1, height: 1 };
export const fixtureStudy = {
	schemaVersion: 1,
	studyId,
	title: "Installed generic-runtime contract fixture",
	sources: [
		{
			id: "fixture-bundled",
			issuingAuthority: "Contract test authority",
			officialTitle: "Bundled fixture source",
			edition: "1",
			revision: null,
			adoptionInstrument: "Fixture instrument 1",
			amendmentsAndErrata: [],
			legalStatus: "active",
			applicabilityStatus: "applicable",
			officialUrl: "https://example.gov.co/fixture-bundled",
			retrievedOn: "2026-07-22",
			redistribution: {
				decision: "bundled",
				localPath: "lib/regulatory/evidence/fixture-source.txt",
				rationale: "Synthetic bytes are committed for runtime contract verification.",
			},
			mediaType: "text/plain",
			pageCount: 1,
			sha256: "90178d0d26dd4435fd32165bbb5f421d434e222cad077799b1635d90c0605a53",
			pages: [
				{ physicalPage: 1, printedPage: "F-1", rotationDegrees: 0, crop: fullPage },
			],
		},
		{
			id: "fixture-external",
			issuingAuthority: "Contract test authority",
			officialTitle: "External fixture applicability source",
			edition: "1",
			revision: "A",
			adoptionInstrument: "Fixture instrument 2",
			amendmentsAndErrata: [],
			legalStatus: "active",
			applicabilityStatus: "conditional",
			officialUrl: "https://example.gov.co/fixture-external",
			retrievedOn: "2026-07-22",
			redistribution: {
				decision: "external-only",
				rationale: "Synthetic pathless source exercises external-only policy.",
			},
			mediaType: "application/pdf",
			pageCount: 1,
			sha256: "0000000000000000000000000000000000000000000000000000000000000000",
			pages: [
				{ physicalPage: 1, printedPage: null, rotationDegrees: 90, crop: fullPage },
			],
		},
	],
	citations: [
		{
			id: "fixture-table",
			sourceDocumentId: "fixture-bundled",
			regionKind: "table",
			physicalPage: 1,
			printedPage: "F-1",
			reference: "Table F-1",
			rect: { left: 0.05, top: 0.05, width: 0.8, height: 0.4 },
			extractedToken: "Table F-1 base 1.00",
			unit: null,
			transformation: null,
			requiredTokens: ["Table F-1"],
		},
		{
			id: "fixture-row",
			sourceDocumentId: "fixture-bundled",
			regionKind: "row",
			physicalPage: 1,
			printedPage: "F-1",
			reference: "Table F-1 row option-a",
			parentCitationId: "fixture-table",
			rect: { left: 0.1, top: 0.1, width: 0.6, height: 0.2 },
			extractedToken: "option-a 1.00",
			unit: null,
			transformation: null,
			requiredTokens: ["option-a"],
		},
		{
			id: "fixture-cell-base",
			sourceDocumentId: "fixture-bundled",
			regionKind: "cell",
			physicalPage: 1,
			printedPage: "F-1",
			reference: "Table F-1 base cell",
			parentCitationId: "fixture-row",
			rect: { left: 0.2, top: 0.15, width: 0.1, height: 0.05 },
			extractedToken: "1.00",
			normalizedValue: 1,
			normalizedNumericValue: 1,
			unit: "g",
			transformation: "decimal parse",
			requiredTokens: ["1.00"],
		},
		{
			id: "fixture-formula",
			sourceDocumentId: "fixture-bundled",
			regionKind: "equation",
			physicalPage: 1,
			printedPage: "F-1",
			reference: "Equation F-1",
			rect: { left: 0.05, top: 0.6, width: 0.8, height: 0.15 },
			extractedToken: "R = B * 2",
			unit: null,
			transformation: null,
			requiredTokens: ["R = B * 2"],
		},
		{
			id: "fixture-applicability",
			sourceDocumentId: "fixture-external",
			regionKind: "applicability",
			physicalPage: 1,
			printedPage: null,
			reference: "Applicability clause",
			rect: { left: 0.1, top: 0.1, width: 0.8, height: 0.2 },
			extractedToken: "Applies to option-a",
			unit: null,
			transformation: null,
			requiredTokens: ["option-a"],
		},
	],
	applicabilityCitationIds: ["fixture-applicability"],
	coverage: { optionIds: ["option-a"], hazardIds: ["hazard-a"], fieldIds: ["base", "result"] },
	values: [
		{
			id: "fixture-value-base",
			optionId: "option-a",
			hazardId: "hazard-a",
			fieldId: "base",
			value: 1,
			unit: "g",
			provenance: "direct-source",
			citationIds: ["fixture-cell-base"],
			transformation: "decimal parse",
		},
		{
			id: "fixture-value-result",
			optionId: "option-a",
			hazardId: "hazard-a",
			fieldId: "result",
			value: 2,
			unit: "g",
			provenance: "derived",
			citationIds: [],
			transformation: null,
			derivedLineage: {
				dependencies: [
					{ valueId: "fixture-value-base", inputCitationIds: ["fixture-cell-base"] },
				],
				formulaCitationId: "fixture-formula",
				formula: "R = B * 2",
				substitution: "1 g * 2",
				result: 2,
				unit: "g",
			},
		},
	],
	rawRows: [
		{
			id: "fixture-raw",
			rowKey: "option-a/hazard-a",
			sourceDocumentId: "fixture-bundled",
			optionId: "option-a",
			hazardId: "hazard-a",
			citationIds: ["fixture-cell-base"],
			fields: { base: 1, result: 2 },
		},
	],
	canonicalRows: [
		{
			id: "fixture-canonical",
			rowKey: "option-a/hazard-a",
			sourceDocumentId: "fixture-bundled",
			optionId: "option-a",
			hazardId: "hazard-a",
			citationIds: ["fixture-cell-base"],
			fields: { base: 1, result: 2 },
			sourceRowIds: ["fixture-raw"],
		},
	],
	overrides: [],
};

export async function check({ repositoryRoot }) {
	return checkEvidenceStudy(fixtureStudy, { repositoryRoot });
}
